name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: pip install -r requirement.txt
    - name: Build package
      run: python setup.py bdist_wheel
    - name: Install databricks-cli
      run: pip install databricks-cli
    - name: Deploy to Databricks
      run: |
        #databricks configure --token "dapi61f701468bffc505edc50e9af2ace6a9-3"
        # Set the Databricks CLI configuration
        echo "[DEFAULT]" > ~/.databrickscfg
        echo "host = https://adb-1128000650204589.9.azuredatabricks.net" >> ~/.databrickscfg
        echo "token = dapi61f701468bffc505edc50e9af2ace6a9-3" >> ~/.databrickscfg
        databricks workspace import --language PYTHON --overwrite "/path/to/main.py" "dist/myproject-0.1-py3-none-any.whl"

