# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Azure Databricks CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Python and Azure CLI
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Azure CLI and Databricks CLI
      run: |
        pip install --upgrade pip
        pip install azure-cli databricks-cli
    
    - name: Authenticate to Azure
      run: |
       az login --service-principal -u 129467ad-cf98-451f-a51d-0575c6ea4bb7 -p UF78Q~K6KuapkVxPxVwjkrUTkTPqDMrdy4lThaHK --tenant e714ef31-faab-41d2-9f1e-e6df4af16ab8
    - name: Deploy notebooks
      run: |
        databricks workspace import_dir ./notebooks /Users/soumya.akunoori@tigeranalytics.com/notebooks
